# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'relevancy-engine'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
         - targets: ['localhost:9090','cadvisor-1:8080','cadvisor-2:8080','cadvisor-3:8080','cadvisor-4:8080','cadvisor-5:8080','cadvisor-6:8080','cadvisor-7:8080','cadvisor-8:8080','node-exporter-1:9100','node-exporter-2:9100','node-exporter-3:9100','node-exporter-4:9100','node-exporter-5:9100','node-exporter-6:9100','node-exporter-7:9100','node-exporter-8:9100', 'haproxy-exporter-server-1:9101', 'haproxy-exporter-server-2:9101', 'es-exporter:9108', 'prometheus-east-1.prometheus.0a11f2b8.cont.dockerapp.io:9090']
